DROP TABLE IF EXISTS TBL_BOOK;
DROP TABLE IF EXISTS TBL_BOOK_VIEWS;

CREATE TABLE TBL_BOOKS (
  BOOK_ID VARCHAR(10) PRIMARY KEY,
  BOOK_NAME VARCHAR(250) NOT NULL,
  DETAILS VARCHAR(250) DEFAULT NULL,
  PRICE NUMERIC(100) DEFAULT NULL,
  IMAGE_URL VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TBL_BOOK_VIEWS (
  BOOK_VIEW_ID INT  NOT NULL,
  BOOK_ID VARCHAR(10)  NOT NULL,
  USER_NAME VARCHAR(250) NOT NULL,
  CONSTRAINT FK_BOOK_BOOK_VIEW FOREIGN KEY (BOOK_ID) REFERENCES TBL_BOOKS(BOOK_ID)
);
